/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  11155111: {
    BaoEnergy: {
      address: "0x85d347AF541132F53CcE42d5336BC48CEDC42200",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "_decision",
              type: "bool",
            },
          ],
          name: "answeredPropose",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "consumer",
              type: "address",
            },
          ],
          name: "newConsumerRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_distributor",
              type: "address",
            },
          ],
          name: "newDistributorAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_distributor",
              type: "address",
            },
          ],
          name: "newProposeAdded",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_cnpj",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_pricePerMonthKWH",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_localId",
              type: "uint256",
            },
          ],
          name: "addDistributor",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_energyConsume",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_pricePerMonth",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_distributor",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_localId",
              type: "uint256",
            },
          ],
          name: "addPropose",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "_decision",
              type: "bool",
            },
          ],
          name: "answerPropose",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_localId",
              type: "uint256",
            },
          ],
          name: "bestOptions",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "cnpj",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "pricePerMonthKWH",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "localId",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "active",
                  type: "bool",
                },
              ],
              internalType: "struct BaoEnergy.Distributor[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "consumerToUserContract",
          outputs: [
            {
              internalType: "address",
              name: "consumer",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "energyConsume",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "pricePerMonth",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "timeStamp",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "localId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "contractDeadLine",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "consumers",
          outputs: [
            {
              internalType: "bool",
              name: "isMemberOfFreeEnergyMarket",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "cnpj",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "localId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "distributors",
          outputs: [
            {
              internalType: "uint256",
              name: "cnpj",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "pricePerMonthKWH",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "localId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getProposes",
          outputs: [
            {
              components: [
                {
                  components: [
                    {
                      internalType: "address",
                      name: "consumer",
                      type: "address",
                    },
                    {
                      internalType: "uint256",
                      name: "energyConsume",
                      type: "uint256",
                    },
                    {
                      internalType: "uint256",
                      name: "pricePerMonth",
                      type: "uint256",
                    },
                    {
                      internalType: "uint256",
                      name: "timeStamp",
                      type: "uint256",
                    },
                    {
                      internalType: "uint256",
                      name: "localId",
                      type: "uint256",
                    },
                    {
                      internalType: "bool",
                      name: "active",
                      type: "bool",
                    },
                    {
                      internalType: "uint256",
                      name: "contractDeadLine",
                      type: "uint256",
                    },
                  ],
                  internalType: "struct BaoEnergy.UserContract",
                  name: "userContract",
                  type: "tuple",
                },
                {
                  internalType: "address",
                  name: "distributor",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "consumer",
                  type: "address",
                },
                {
                  internalType: "bool",
                  name: "answered",
                  type: "bool",
                },
              ],
              internalType: "struct BaoEnergy.Propose[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "localIdToDistributors",
          outputs: [
            {
              internalType: "uint256",
              name: "cnpj",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "pricePerMonthKWH",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "localId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "localToContract",
          outputs: [
            {
              internalType: "address",
              name: "consumer",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "energyConsume",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "pricePerMonth",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "timeStamp",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "localId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "contractDeadLine",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "proposes",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "consumer",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "energyConsume",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "pricePerMonth",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "timeStamp",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "localId",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "active",
                  type: "bool",
                },
                {
                  internalType: "uint256",
                  name: "contractDeadLine",
                  type: "uint256",
                },
              ],
              internalType: "struct BaoEnergy.UserContract",
              name: "userContract",
              type: "tuple",
            },
            {
              internalType: "address",
              name: "distributor",
              type: "address",
            },
            {
              internalType: "address",
              name: "consumer",
              type: "address",
            },
            {
              internalType: "bool",
              name: "answered",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_cnpj",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_localId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "_isMemberOfFreeEnergyMarket",
              type: "bool",
            },
          ],
          name: "registerConsumer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
